### ISSUE TITLE
echo.jl example raises "ERROR: type WSClient has no field handler_proxy"

### ISSUE THREAD

**Issue by amckay1** [dandeliondeathray/DandelionWebSockets.jl#42]
Hi,

Running the echo.jl example code, I get the error <code>ERROR: type WSClient has no field handler_proxy</code> when I attempt to initialize the client: <code>client = WSClient()</code>

Just a heads up, thank you!

Specs:
Julia 0.6.2
DandelionWebSockets 0.1.1

**Comment by erikedin** [comment]
Thank you, this is now fixed in master. It was a show method that tried to access an old field. I would not have found this easily, because I rely on my unit tests these days, and they apparently do not cover this method.
