### ISSUE TITLE
Printing and i/o is not thread safe

### ISSUE THREAD

**Issue by alessandrousseglioviretta** [dandeliondeathray/DandelionWebSockets.jl#6]
It might be worthwhile noting in the documentation that using `println` in the `state_...` callbacks might lead to unexpected behaviour, including segfaults, see https://github.com/JuliaLang/julia/issues/17388

**Comment by erikedin** [comment]
I was not aware of that, so thank you for bringing that to my attention! I've added a note on it in the README, but I will also make an effort to fix this in the examples.
